name: nomads
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  collection: ^1.19.1
  flutter_hooks:
  flutter_secure_storage: ^10.0.0
  hooks_riverpod: ^3.1.0
  go_router: ^17.0.1
  intl: ^0.20.2
  morphable_shape: ^2.0.0
  shared_preferences: ^2.5.4
  sizer: ^3.1.3
  ulid: ^2.0.1

dev_dependencies:
  # flame_lint: ^1.4.2
  flutter_lints: ^6.0.0
  riverpod_lint: ^3.1.0

flutter:
  generate: true
  uses-material-design: true

  shaders:
    - shaders/burn.frag
    - shaders/fog.frag
    - shaders/freezed.frag
    - shaders/holo.frag
    - shaders/ornament.frag
    - shaders/kyrgyz_dissolve.frag

  assets:
    # - assets/cards/
    - assets/images/
    # - assets/images/cards/
    # - assets/textures/
